//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepoResult
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_Aq_Calibration
    {
        public int id { get; set; }
        public string Barcode { get; set; }
        public Nullable<bool> Pass { get; set; }
        public Nullable<short> count { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
